"""prva migracia

Revision ID: fe5852b93ca9
Revises: 
Create Date: 2022-04-28 14:37:13.912203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5852b93ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('localized_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('nick', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_region_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tower_status_radiant', sa.Integer(), nullable=True),
    sa.Column('tower_status_dire', sa.Integer(), nullable=True),
    sa.Column('barracks_status_radiant', sa.Integer(), nullable=True),
    sa.Column('barracks_status_dire', sa.Integer(), nullable=True),
    sa.Column('first_blood_time', sa.Integer(), nullable=True),
    sa.Column('game_mode', sa.Integer(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('negative_votes', sa.Integer(), nullable=True),
    sa.Column('positive_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_region_id'], ['cluster_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('total_wins', sa.Integer(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('trueskill_mu', sa.Numeric(), nullable=True),
    sa.Column('trueskill_sigma', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches_players_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('player_slot', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('gold_spent', sa.Integer(), nullable=True),
    sa.Column('gold_per_min', sa.Integer(), nullable=True),
    sa.Column('xp_per_min', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('denies', sa.Integer(), nullable=True),
    sa.Column('last_hits', sa.Integer(), nullable=True),
    sa.Column('stuns', sa.Integer(), nullable=True),
    sa.Column('hero_damage', sa.Integer(), nullable=True),
    sa.Column('hero_healing', sa.Integer(), nullable=True),
    sa.Column('tower_damage', sa.Integer(), nullable=True),
    sa.Column('item_id_1', sa.Integer(), nullable=True),
    sa.Column('item_id_2', sa.Integer(), nullable=True),
    sa.Column('item_id_3', sa.Integer(), nullable=True),
    sa.Column('item_id_4', sa.Integer(), nullable=True),
    sa.Column('item_id_5', sa.Integer(), nullable=True),
    sa.Column('item_id_6', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('leaver_status', sa.Integer(), nullable=True),
    sa.Column('xp_hero', sa.Integer(), nullable=True),
    sa.Column('xp_creek', sa.Integer(), nullable=True),
    sa.Column('xp_roshan', sa.Integer(), nullable=True),
    sa.Column('xp_other', sa.Integer(), nullable=True),
    sa.Column('gold_other', sa.Integer(), nullable=True),
    sa.Column('gold_death', sa.Integer(), nullable=True),
    sa.Column('gold_buyback', sa.Integer(), nullable=True),
    sa.Column('gold_abandon', sa.Integer(), nullable=True),
    sa.Column('gold_sell', sa.Integer(), nullable=True),
    sa.Column('gold_destroying_structure', sa.Integer(), nullable=True),
    sa.Column('gold_killing_heroes', sa.Integer(), nullable=True),
    sa.Column('gold_killing_creeps', sa.Integer(), nullable=True),
    sa.Column('gold_killing_roshan', sa.Integer(), nullable=True),
    sa.Column('gold_killing_couriers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['item_id_1'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id_2'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id_3'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id_4'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id_5'], ['items.id'], ),
    sa.ForeignKeyConstraint(['item_id_6'], ['items.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamfights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('start_teamfight', sa.Integer(), nullable=True),
    sa.Column('end_teamfight', sa.Integer(), nullable=True),
    sa.Column('last_death', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability_upgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('nick', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_player_detail_id_1', sa.Integer(), nullable=True),
    sa.Column('match_player_detail_id_2', sa.Integer(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id_1'], ['matches_players_details.id'], ),
    sa.ForeignKeyConstraint(['match_player_detail_id_2'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('unit_order_none', sa.Integer(), nullable=True),
    sa.Column('unit_order_move_to_position', sa.Integer(), nullable=True),
    sa.Column('unit_order_move_to_target', sa.Integer(), nullable=True),
    sa.Column('unit_order_attack_move', sa.Integer(), nullable=True),
    sa.Column('unit_order_attack_target', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_position', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_target', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_target_tree', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_no_target', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_toggle', sa.Integer(), nullable=True),
    sa.Column('unit_order_hold_position', sa.Integer(), nullable=True),
    sa.Column('unit_order_train_ability', sa.Integer(), nullable=True),
    sa.Column('unit_order_drop_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_give_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_pickup_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_pickup_rune', sa.Integer(), nullable=True),
    sa.Column('unit_order_purchase_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_sell_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_disassemble_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_move_item', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_toggle_auto', sa.Integer(), nullable=True),
    sa.Column('unit_order_stop', sa.Integer(), nullable=True),
    sa.Column('unit_order_buyback', sa.Integer(), nullable=True),
    sa.Column('unit_order_glyph', sa.Integer(), nullable=True),
    sa.Column('unit_order_eject_item_from_stash', sa.Integer(), nullable=True),
    sa.Column('unit_order_cast_rune', sa.Integer(), nullable=True),
    sa.Column('unit_order_ping_ability', sa.Integer(), nullable=True),
    sa.Column('unit_order_move_to_direction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('lh', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('lh', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teamfights_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamfight_id', sa.Integer(), nullable=True),
    sa.Column('match_player_detail_id', sa.Integer(), nullable=True),
    sa.Column('buyback', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('gold_delta', sa.Integer(), nullable=True),
    sa.Column('xp_start', sa.Integer(), nullable=True),
    sa.Column('xp_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_detail_id'], ['matches_players_details.id'], ),
    sa.ForeignKeyConstraint(['teamfight_id'], ['teamfights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamfights_players')
    op.drop_table('purchase_logs')
    op.drop_table('player_times')
    op.drop_table('player_actions')
    op.drop_table('game_objectives')
    op.drop_table('chats')
    op.drop_table('ability_upgrades')
    op.drop_table('teamfights')
    op.drop_table('matches_players_details')
    op.drop_table('player_ratings')
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('items')
    op.drop_table('heroes')
    op.drop_table('cluster_regions')
    op.drop_table('abilities')
    # ### end Alembic commands ###
